### PR TITLE
fix: keep track of last opened page

### LINKED ISSUE #1451: "Open Web UI at Launch" stays at  `/blank` instead of `/`
WebUI seems to have some leftovers related to settings, which produce an error:

> 2020-04-27-135139_1330x435_scrot

### PR DESCRIPTION
**Pull request by hacdias**
Fixes #1451. Keeps track of the last opened page so every time we need to refresh because a change on the IPFS status, we can keep the user on the same page. The visibility (`/blank` handling) is taken care on the `preload.js`.

License: MIT
Signed-off-by: Henrique Dias <hacdias@gmail.com>

### CODE REVIEW

File: src/webui/index.js [hunk 1]
```diff
@@ -126,6 +127,7 @@ module.exports = async function (ctx) {
       apiAddress = ipfsd.apiAddr
       url.searchParams.set('api', apiAddress)
       updateLanguage()
+      console.log(url.toString())
```
Comment (lidel) [inline src/webui/index.js:130]:
```suggestion
```
