### PR TITLE
fix: added daemon functions to the auto-updater

### LINKED ISSUE #1375: stopIpfs is not a function
I clicked update IPFS and an error window appeared.

**Specifications**

- **OS**: win32
- **IPFS Desktop Version**: 0.10.3
- **Electron Version**: 7.1.11
- **Chrome Version**: 78.0.3904.130

**Error**

```
TypeError: stopIpfs is not a function
    at _callee$ (D:\network\IPFS\resources\app.asar\out\auto-updater\quit-and-install.js:42:20)
    at tryCatch (D:\network\IPFS\resources\app.asar\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (D:\network\IPFS\resources\app.asar\node_modules\regenerator-runtime\runtime.js:271:22)
    at Generator.prototype.<computed> [as next] (D:\network\IPFS\resources\app.asar\node_modules\regenerator-runtime\runtime.js:97:21)
    at asyncGeneratorStep (D:\network\IPFS\resources\app.asar\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\network\IPFS\resources\app.asar\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at D:\network\IPFS\resources\app.asar\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at D:\network\IPFS\resources\app.asar\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at _quitAndInstall (D:\network\IPFS\resources\app.asar\out\auto-updater\quit-and-install.js:58:26)
```

### LINKED ISSUE #1496: err-0.11.1
Please describe what you were doing when this error happened.

**Specifications**

- **OS**: win32
- **IPFS Desktop Version**: 0.11.1
- **Electron Version**: 8.2.4
- **Chrome Version**: 80.0.3987.165

**Error**

```
TypeError: stopIpfs is not a function
    at quitAndInstall (C:\Users\V\AppData\Local\Programs\IPFS Desktop\resources\app.asar\src\auto-updater\quit-and-install.js:13:24)
    at Immediate.<anonymous> (C:\Users\V\AppData\Local\Programs\IPFS Desktop\resources\app.asar\src\auto-updater\index.js:87:9)
    at processImmediate (internal/timers.js:439:21)
```

### LINKED ISSUE #1508: Auto-update breaks package managers
> Please describe what you were doing when this error happened.

Opening the computer.

**Specifications**

- **OS**: win32
- **IPFS Desktop Version**: 0.11.2
- **Electron Version**: 8.2.4
- **Chrome Version**: 80.0.3987.165

```yaml
OS: Windows 10 Pro x86_64
Host: System manufacturer
Kernel: 10.0.18363
Uptime: 4 days, 22 hours, 49 mins
Shell: bash 4.4.23
Resolution: 1920x1080
DE: Aero
WM: Explorer
WM Theme: Roamed
CPU: Intel i5-3570K (4) @ 3.468GHz
GPU: NVIDIA GeForce GTX 660 Ti
Memory: 17124MiB / 24519MiB
```

```yaml
Name: ipfs-desktop
Description: A desktop client for IPFS.
Version: 0.11.2
Website: https://github.com/ipfs-shipyard/ipfs-desktop
License: MIT (https://spdx.org/licenses/MIT.html)
Manifest:
  C:\Users\natob\scoop\buckets\extras\bucket\ipfs-desktop.json
Installed:
  C:\ProgramData\scoop\apps\ipfs-desktop\0.11.2 *global*
```

```yaml
go-ipfs version: 0.6.0-dev
Repo version: 9
System version: amd64/windows
Golang version: go1.14.3
```

**Error**

image

image

```typescript
TypeError: stopIpfs is not a function
    at quitAndInstall (C:\ProgramData\scoop\apps\ipfs-desktop\0.11.2\resources\app.asar\src\auto-updater\quit-and-install.js:13:24)
    at Immediate.<anonymous> (C:\ProgramData\scoop\apps\ipfs-desktop\0.11.2\resources\app.asar\src\auto-updater\index.js:87:9)
    at processImmediate (internal/timers.js:439:21)
```

**Related**

https://github.com/ipfs-shipyard/ipfs-desktop/issues/691, https://github.com/lukesampson/scoop-extras/issues/1597

### PR DESCRIPTION
**Pull request by rafaelramalho19**
Fixes #1508, fixes #1496, fixes #1375

- I'm not able to test this for sure because autoUpdater doesn't work on dev mode.

The problem was that the autoUpdater was trying to access the `stopIpfs` from the context (`ctx` variable), but that would only be initialized with the functions after `setupDaemon` has been executed.

### CODE REVIEW

File: src/auto-updater/quit-and-install.js [hunk 1]
```diff
@@ -10,9 +11,14 @@ module.exports = async function quitAndInstall ({ stopIpfs }) {
...
+    const status = await stopIpfs()
 
-  if (status === STATUS.STOPPING_FAILED || status === STATUS.STOPPING_FINISHED) {
+    if (status === STATUS.STOPPING_FAILED || status === STATUS.STOPPING_FINISHED) {
+      autoUpdater.quitAndInstall(true, true)
+    }
+  } catch (err) {
+    logger.error(err)
     autoUpdater.quitAndInstall(true, true)
   }
```
Comment (lidel) [inline src/auto-updater/quit-and-install.js:23]: I am probably too paranoid, but if `stopIpfs` returns anything other than [`6` or `2`](https://github.com/ipfs-shipyard/ipfs-desktop/blob/v0.11.3/src/daemon/consts.js) , nothing happens – no error, no update :grimacing: 

Is there any downside to just ignoring the status like this, and making `stopIpfs` a best-effort operation (that can't impact update mechanism in any way)?

```js
  try {
    await stopIpfs()
  } catch (err) {
    logger.error('unexpected error during stopIpfs', err)   
  }
  autoUpdater.quitAndInstall(true, true)
```

Comment (rafaelramalho19) [reply src/auto-updater/quit-and-install.js]: Makes sense! Also added a logger info to help debug future problems with stopIpfs
